### ISSUE TITLE
Official repository

### ISSUE THREAD

**Issue by timorzadir** [jstedfast/HtmlAgilityPack#1]
Is this the current, official repository for [HtmlAgilityPack on NuGet](https://www.nuget.org/packages/HtmlAgilityPack/)?

**Comment by jstedfast** [comment]
Nope, this was just my fork a few years ago :-)

It's pretty out of date.

**Comment by jstedfast** [comment]
I think what you want is this: https://htmlagilitypack.codeplex.com/
