### ISSUE TITLE
HtmlAttribute.Value should use HtmlEntity.DeEntitize when setting _value

### ISSUE THREAD

**Issue by drbsoftware** [jstedfast/HtmlAgilityPack#3]
The attribute data-foo="&amp;quot;Hello&amp;quot;" should result in "Hello", not &amp;quot;Hello&amp;quot;
I think the fix is:
```
        public string Value
        {
            get
            {
                if (_value == null)
                {
                    _value = HtmlEntity.DeEntitize(ownerdocument.Text.Substring(_valuestartindex, _valuelength));
                }
                return _value;
            }
            set
            {
                _value = HtmlEntity.DeEntitize(value);
                if (_ownernode != null)
                {
                    _ownernode._innerchanged = true;
                    _ownernode._outerchanged = true;
                }
            }
        }
```

**Comment by jstedfast** [comment]
You are submitting your bug report/patch to the wrong project. This is an old old old old old fork of HtmlAgilityPack that has not been updated in like 5 or 6 years.

**Comment by drbsoftware** [comment]
Thank you.  Where do I find the most recent one?

David

 

David Robinson Consulting, Inc.

Brookline, MA  02446

781-862-8763

**Comment by jstedfast** [comment]
I honestly don't know, I'd have to google for it.
