### ISSUE TITLE
calling RemoveAt on an instance of HtmlNodeCollection throwing exception

### ISSUE THREAD

**Issue by goforgold** [jstedfast/HtmlAgilityPack#4]
I've a valid instance of `HtmlNodeCollection` having 78 member (retrieved using `.Count`) as below:

`var regionRows = ...`

I need to remove very first element from the `regionRows`.

I tried calling `regionRows.RemoveAt(0)`, but it is throwing an exception `System.NullReferenceException: Object reference not set to an instance of an object`.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at HtmlAgilityPack.HtmlNodeCollection.RemoveAt(Int32 index) in ..... 250
```

Any suggestion? I want to do it without LINQ.

**Comment by jstedfast** [comment]
This is an ancient (6 years old) fork of the official HtmlAgilityPack project, it's not the real project.

**Comment by goforgold** [comment]
Yeah 😀

Noticed already and reported the issue on the real repo.
