### ISSUE TITLE
HtmlWeb.LoadFromBrowser error

### ISSUE THREAD

**Issue by hugolim** [jstedfast/HtmlAgilityPack#5]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'HtmlWeb.LoadFromBrowser(string, Func<string, bool>)' and 'HtmlWeb.LoadFromBrowser(string, Func<object, bool>)'	HtmlAgilityPack.fx.4.5	E:\git\MagentoLink\WMSMagentoExtractionScript [Cargo Crew]\References\html-agility-pack-master\src\HtmlAgilityPack\HtmlWeb.cs	2211	Active

Please assit?
Thanks.

**Comment by jstedfast** [comment]
This is a fork of HtmlAgilityPack which has not been updated for something like 6 years. You probably want to submit this against the official HtmlAgilityPack project (assuming this bug exists in that version) :)
