### ISSUE TITLE
HtmlAttribute.Value

### ISSUE THREAD

**Issue by Mx-Wolf** [jstedfast/HtmlAgilityPack#6]
var doc = new HtmlDocument();
            var html = doc.CreateElement("span"); 
            html.Attributes.Add("data-marker", null);
            var nullValue = html.Attributes[0].Value;
NullReferenceException at _value = _ownerdocument.**Text**.Substring(_valuestartindex, _valuelength);
**Text** is null.

**Comment by jstedfast** [comment]
This is a fork of HtmlAgilityPack which has not been updated for something like 6 years. You probably want to submit this against the official HtmlAgilityPack project (assuming this bug exists in that version) :)
